### ISSUE TITLE
Error Can't find variable: _setGlobalConsole when import

### ISSUE THREAD

**Issue by AlexandreHosek** [rainbow-me/react-native-animated-charts#13]
Hi,

I tried to create a new react-native project and when I try to import :
 improt {ChartDot, ChartPath, ChartPathProvider, monotoneCubicInterpolation} from '@rainbow-me/animated-charts';

I get this error : 
ReferenceError: Can't find variable: _setGlobalConsole
(node:24622) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [HasteMap]. Use emitter.setMaxListeners() to increase limit

![image](https://user-images.githubusercontent.com/33135219/103357763-3fce8580-4ab4-11eb-9f09-9f9e8af88ca7.png)

Is it an error you encountered before ? 
I added the lastest react-native-reanimated and the babel plugin. 

Thank you for any help :)

**Comment by nandorojo** [comment]
I'm pretty sure this is an issue with reanimated's new version. If I recall correctly, it's from RC 1. What if you downgrade to RC 0?

See https://github.com/software-mansion/react-native-reanimated/issues/1546

**Comment by alexeliacik** [comment]
Same here!

**Comment by nandorojo** [comment]
I tried downgrading to `2.0.0-rc.0` but I'm still seeing this. I've cleared the cache and done everything recommended [here](https://github.com/software-mansion/react-native-reanimated/issues/1546). The problem happens specifically when I import this library. If I use `moti`, which also relies on reanimated, there aren't any issues.

Has anyone solved this?

**Comment by nandorojo** [comment]
Here are my repro steps:

1. Create reanimated 2 starter: `npx create-react-native-app -t with-moti`
2. Install animated charts: `yarn add @rainbow-me/animated-charts`
3. Import the example app:

```jsx
// App.js
import React from 'react'
import { Dimensions, View } from 'react-native'
import { ChartDot, ChartPath, ChartPathProvider, monotoneCubicInterpolation } from '@rainbow-me/animated-charts'

export const { width: SIZE } = Dimensions.get('window')

export const data = [
  { x: 1453075200, y: 1.47 },
  { x: 1453161600, y: 1.37 },
  { x: 1453248000, y: 1.53 },
  { x: 1453334400, y: 1.54 },
  { x: 1453420800, y: 1.52 },
  { x: 1453507200, y: 2.03 },
  { x: 1453593600, y: 2.1 },
  { x: 1453680000, y: 2.5 },
  { x: 1453766400, y: 2.3 },
  { x: 1453852800, y: 2.42 },
  { x: 1453939200, y: 2.55 },
  { x: 1454025600, y: 2.41 },
  { x: 1454112000, y: 2.43 },
  { x: 1454198400, y: 2.2 }
]

const points = monotoneCubicInterpolation(data)(40)

const BasicExample = () => (
  <View style={{ backgroundColor: 'black' }}>
    <ChartPathProvider data={{ points, smoothingStrategy: 'bezier' }}>
      <ChartPath height={SIZE / 2} stroke="yellow" width={SIZE} />
      <ChartDot style={{ backgroundColor: 'blue' }} />
    </ChartPathProvider>
  </View>
)

export default BasicExample
```

Here's the resulting error:

<img width="481" alt="Screen Shot 2021-02-24 at 2 20 36 PM" src="https://user-images.githubusercontent.com/13172299/109054113-7fc47a00-76ab-11eb-82d8-29a1d18677d7.png">

**Comment by nandorojo** [comment]
I solved this by copying the source code from `rainbow`'s repo into my app, instead of using the version from NPM.

You can find the `src` code here: https://github.com/rainbow-me/rainbow/tree/develop/src/react-native-animated-charts

**Comment by osdnk** [comment]
Yes, I'll do this doon

**Comment by osdnk** [comment]
done
