### ISSUE TITLE
TurboModuleRegistry.getEnforcing(...) Error

### ISSUE THREAD

**Issue by AlexandreHosek** [rainbow-me/react-native-animated-charts#18]
Hello,

I have no problem using the library on ios it works perfectly fine, but im not able to use it on android I get this error:

![image](https://user-images.githubusercontent.com/33135219/104325122-8aa2c100-54e8-11eb-9f4d-e33895d841d3.png)

Did you encounter this error yet ?

Thank you for any help

**Comment by AlexandreHosek** [comment]
Ok my bad didn't follow well the documentation !

**Comment by high-performance-hery** [comment]
@AlexandreHosek do you remember how you solved it? I'm having this issues as well because we're not using TurboModules
