### ISSUE TITLE
#ask Getting callback value of selected line

### ISSUE THREAD

**Issue by rinoarmadiaz** [rainbow-me/react-native-animated-charts#29]
Hi guys, i'm having difficulties on getting the callback (X or Y) of selected path, how can i get the value so i can update my views respectively? 

thanks!

**Comment by rinoarmadiaz** [comment]
found the solution, i just realised we're using Context for wrapping the charts,

so you can wrap using the ChartProvider and access the context data from ChartContext,

since the context using the animated hooks, you can use ```useDerivedValue``` to trigger the changes and ```useAnimated``` style to style your View respectively

**Comment by ImBeCiliC** [comment]
@rinoarmadiaz could you elaborate a little more on how you fixed the issue. Didn't understood your approach with the useDerivedValue maybe you could add an example?

Thank you

**Comment by ajimae** [comment]
> found the solution, i just realised we're using Context for wrapping the charts,
> 
> so you can wrap using the ChartProvider and access the context data from ChartContext,
> 
> since the context using the animated hooks, you can use `useDerivedValue` to trigger the changes and `useAnimated` style to style your View respectively

If you won't elaborate on an answer so that others like me can understand. Then you better keep mute.
