### ISSUE TITLE
Is It Possible To Show nativePoints as a ChartPath When isActive is Triggered?

### ISSUE THREAD

**Issue by rinoarmadiaz** [rainbow-me/react-native-animated-charts#32]
Hi! i really love this library, made some tweaks here and there in order to match user requirement, but right now i'm having difficulties, 

is it possible to show our **default points** rather than interpolated one, when user are pressing the chart (isActive triggered)

Something like this,
![Alt Text](https://media.giphy.com/media/3QEUKv2snil8YfOLio/giphy.gif)

by default it's still showing interpolated smoothen path, but when user are triggering the isActive (pressing the chart), i'd like to show the **Default** points data for more accurate representation (more jagged edges).

If you know, please advice :)

Thanks!!

**Comment by rinoarmadiaz** [comment]
nvm, solved it also lol.

i've override the isActive callback from the listener, and give  the data with the non-interpolated (original) data.

thanks for this beautiful library tho 👍🏻👍🏻

**Comment by bigyankarki** [comment]
Hey do you mind sharing how you got the data to calculate change in price from the chart? I could get prices from y axis, but not sure how to get the first data from the chart/array. Are you using useChartData hooks?
