### ISSUE TITLE
Decleration issue when importing @rainbow-me/animated-charts

### ISSUE THREAD

**Issue by Developer3SiegeTechnology** [rainbow-me/react-native-animated-charts#34]
When I import 

`import {
  ChartDot,
  ChartPath,
  ChartPathProvider,
  monotoneCubicInterpolation,
} from '@rainbow-me/animated-charts';`

I seem to be getting an error saying - "Could not find a declaration file for module '@rainbow-me/animated-charts. Because of that, the graph is not showing.

**Comment by M4FFS** [comment]
Same here

**Comment by Developer3SiegeTechnology** [comment]
> Same here

So I actually found a solution: 

The import issue is only a warning I'm guessing and the reason that my graph wasn't working was because i had 

monotoneCubicInterpolation(data)(40);

instead of --

monotoneCubicInterpolation({ data, range: 40 })

adding the range and {} fixed the issue for me! Hope that helped.
