### ISSUE TITLE
hapticsEnabled does not work

### ISSUE THREAD

**Issue by kanavi9527** [rainbow-me/react-native-animated-charts#35]
<ChartPath
    height={SIZE / 3}
    width={SIZE}
    stroke="#ffa694"
    strokeWidth={3.5}
    selectedStrokeWidth={3}
    hapticsEnabled
    smoothingWhileTransitioningEnabled={.5}
/>

error: 
Tried to synchronously call anonymous function from a different thread.

Occurred in worklet location: ...../@rainbow-me/animated-charts/src/charts/linear/ChartPath.js (26:0)

Possible solutions are:
a) If you want to synchronously execute this method, mark it as a Worklet
b) If you want to execute this method on the JS thread, wrap it using runOnJS

**Comment by osdnk** [comment]
I fixed this on main branch!
