### ISSUE TITLE
Does this work with expo?

### ISSUE THREAD

**Issue by asp3** [rainbow-me/react-native-animated-charts#5]
I currently have a managed expo application (expo 38) and was wondering if this library could be used without ejecting!

**Comment by outaTiME** [comment]
Hi @asp3, only available with SDK 39:

https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2-alpha

**Comment by osdnk** [comment]
I wouldn't recommend now but technically yes
