### ISSUE TITLE
Black background from example without main line path

### ISSUE THREAD

**Issue by andreibahachenka** [rainbow-me/react-native-animated-charts#54]
Hi all, 
I have the same issues as the person on github

https://stackoverflow.com/questions/68184815/rainbow-me-react-native-chart-not-showing-path
[](https://stackoverflow.com/questions/68184815/rainbow-me-react-native-chart-not-showing-path)

I've copied everything from the example, but don't see the line and tooltip, only black background
Of course, I have this line from example
const points = monotoneCubicInterpolation({ data, range: 40 })

console.log(points) => [], but why?
console.log(data) => array of objects with my data

Is there any solution? 

I'm using 
- "expo": "^41.0.0",
- "react-native-reanimated": "^2.1.0",
- "@rainbow-me/animated-charts": "^1.0.0-alpha.6",

**Comment by b0n1q** [comment]
https://stackoverflow.com/questions/68184815/rainbow-me-react-native-chart-not-showing-path
