### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by andreibahachenka** [rainbow-me/react-native-animated-charts#58]
Hi All
When I try to formate date using dayjs or when I try to format currency using Intl.NumberFormat()
I've got the following error

Code sample
![image](https://user-images.githubusercontent.com/26281760/146164814-6a77cf62-cf7b-4e26-9e3a-304651af66e0.png)

Could anyone help what to do?

![image](https://user-images.githubusercontent.com/26281760/146164912-42ec2903-e2b7-42e0-bdb2-011232dc31d9.png)

**Comment by aerielcruz** [comment]
@b0n1q I'm having the same problem. How did you fix this?
