### ISSUE TITLE
Wired splines representation when stable data

### ISSUE THREAD

**Issue by outaTiME** [rainbow-me/react-native-animated-charts#6]
Hi @osdnk, 

I'm doing some tests with stable data (without variation) and the graph looks weird:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/140472/97119371-8daec200-16ee-11eb-8f16-b899b02be45e.png">

The line dotted in purple is the path of react-native-animated-charts (I don't know why it does those splines), and on the other hand the chart in the background is the representation of victory charts using the same dataset.

Here I attach dataset and ChartPathProvider configuration, it would be very useful if you can help me @osdnk.

```js
const data = [
  {
    "x": 0,
    "y": 138.35,
  },
  {
    "x": 1,
    "y": 138.35,
  },
  {
    "x": 2,
    "y": 138.35,
  },
  {
    "x": 3,
    "y": 138.35,
  },
  {
    "x": 4,
    "y": 138.35,
  },
  {
    "x": 5,
    "y": 138.35,
  },
  {
    "x": 6,
    "y": 138.35,
  },
];
const points = React.useMemo(
  () => ({
    points: interpolator({
      data,
      includeExtremes: true,
      range: 300, // ~1 year of working days
    }),
    smoothingStrategy: 'bezier',
  }),
  [data]
);
<ChartPathProvider data={points}>
  <ChartPath height={SIZE / 2} stroke="yellow" width={SIZE} />
</ChartPathProvider>
```

Thanks

**Comment by outaTiME** [comment]
BTW, It happens only when the data is stable, otherwise it will look perfectly (or quite approximate) to the monotoneX interpolation of d3-shape.

<img width="422" alt="CleanShot 2020-10-25 at 18 52 24@2x" src="https://user-images.githubusercontent.com/140472/97120634-352ff280-16f7-11eb-9cf2-36e9c23563f5.png">

I tried various combinations, changing the interpolator, smoothingStrategy, includeExtremes, removePointsSurroundingExtremes and all with no luck, maybe the error is in "ChartPath.js".

**Comment by osdnk** [comment]
Hey, many thanks. Let me quickly take a look

**Comment by osdnk** [comment]
Hey,
Use the newest version and adjust your code by adding y bounds:

```jsx
const data = [
  {
    "x": 0,
    "y": 138.35,
  },
  {
    "x": 1,
    "y": 138.35,
  },
  {
    "x": 2,
    "y": 138.35,
  },
  {
    "x": 3,
    "y": 138.35,
  },
  {
    "x": 4,
    "y": 138.35,
  },
  {
    "x": 5,
    "y": 138.35,
  },
  {
    "x": 6,
    "y": 138.35,
  },
];
const points = React.useMemo(
  () => ({
    points: interpolator({
      data,
      includeExtremes: true,
      range: 300, // ~1 year of working days
      yRange: [136, 140] // ADD THIS!
    }),
    smoothingStrategy: 'bezier',
  }),
  [data]
);
<ChartPathProvider data={points}>
  <ChartPath height={SIZE / 2} stroke="yellow" width={SIZE} />
</ChartPathProvider>
```

**Comment by outaTiME** [comment]
Awesome Michał 🙌
thanks for your time and for this new functionality for minY and maxY customization 🔥🔥🔥

right now I try this new version

**Comment by outaTiME** [comment]
@osdnk works perfectly, except that the `yRange` goes outside of points 🙃

I leave the updated code:

```js
const data = [
  {
    "x": 0,
    "y": 138.35,
  },
  {
    "x": 1,
    "y": 138.35,
  },
  {
    "x": 2,
    "y": 138.35,
  },
  {
    "x": 3,
    "y": 138.35,
  },
  {
    "x": 4,
    "y": 138.35,
  },
  {
    "x": 5,
    "y": 138.35,
  },
  {
    "x": 6,
    "y": 138.35,
  },
];
const points = React.useMemo(
  () => ({
    points: interpolator({
      data,
      includeExtremes: true,
      range: 300, // ~1 year of working days
    }),
    yRange: [136, 140], // ADD THIS!
    smoothingStrategy: 'bezier',
  }),
  [data]
);
<ChartPathProvider data={points}>
  <ChartPath height={SIZE / 2} stroke="yellow" width={SIZE} />
</ChartPathProvider>
```

thanks again !!!
