### ISSUE TITLE
Show min and max values in graph

### ISSUE THREAD

**Issue by skeie** [rainbow-me/react-native-animated-charts#71]
Hey,

First off, thanks for this amazing graph library, it works great! I was wondering if there are any ways to show the min and max values in the graph?

 shown in the picture below with a red arrow

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1346122/156243830-504a2df5-3005-422b-9c99-8aa20a8331fc.png">

**Comment by nunoplima** [comment]
Hi there!

This should get you started, check Labels: https://github.com/rainbow-me/rainbow/blob/develop/src/components/value-chart/ExtremeLabels.js

**Comment by skeie** [comment]
Thank you :)
