### ISSUE TITLE
Random black background appearing

### ISSUE THREAD

**Issue by colinfran** [rainbow-me/react-native-animated-charts#94]
I do not have any background styling set. background should be completely white.

chart is showing weird black background.

anyone know how to fix?

<img width="346" alt="Screen Shot 2023-03-23 at 7 18 32 PM" src="https://user-images.githubusercontent.com/16205865/227408900-3f72896c-28a2-4afb-bdc9-27cc2768522f.png">

**Comment by andreibahachenka** [comment]
what was the fix?
